### ISSUE TITLE
The red line indicating the barrel isn't cleared on new levels

### ISSUE THREAD

**Issue by dundargoc** [seandewar/killersheep.nvim#1]
Hi! Thank you for such a fantastic plugin! I've had a lot of fun with this but I've encountered a bug.

The red line that indicates the barrel isn't cleared when reaching a new level. Maybe this screenshot will help:

![Screenshot from 2022-03-06 10-44-19](https://user-images.githubusercontent.com/33953936/156917905-27a8c032-fde3-464d-af40-80576a9ad46b.png)

**Comment by seandewar** [comment]
oops I forgor 💀
