### ISSUE TITLE
How to change keybindings ?

### ISSUE THREAD

**Issue by veyxov** [seandewar/killersheep.nvim#4]
I am on a different kyboard layout (colemak) and want to change the movement keys. Is there some kind of configuration ?

**Comment by seandewar** [comment]
I've just added the ability to change some settings via calling a `require("killersheep").setup()` function:

For example, the default settings look like:
```lua
require("killersheep").setup {
  gore = true,           -- Enables/disables blood and gore.
  keymaps = {
    move_left = "h",     -- Keymap to move cannon to the left.
    move_right = "l",    -- Keymap to move cannon to the right.
    shoot = "<Space>",   -- Keymap to shoot the cannon.
  },
}
```
(Any omitted option will be set to its default value)

Thanks for the suggestion. Hope this helps! :)
